// <auto-generated />
using GLR_Backend_API_NET_CORE;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using MySql.Data.EntityFrameworkCore.Storage.Internal;
using System;

namespace GLR_Backend_API_NET_CORE.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20180727070956_MyFirstMigration")]
    partial class MyFirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("GLR_Backend_API_NET_CORE.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("DepartmentId");

                    b.Property<string>("Name");

                    b.Property<int?>("StudentId");

                    b.Property<int?>("TeacherId");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("GLR_Backend_API_NET_CORE.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int?>("OrganizationId");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("GLR_Backend_API_NET_CORE.Models.Leacture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CourseId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Leactures");
                });

            modelBuilder.Entity("GLR_Backend_API_NET_CORE.Models.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("GLR_Backend_API_NET_CORE.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int?>("departmentId");

                    b.HasKey("Id");

                    b.HasIndex("departmentId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("GLR_Backend_API_NET_CORE.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("DepartmentId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("GLR_Backend_API_NET_CORE.Models.UserInfo", b =>
                {
                    b.Property<string>("Email")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Password");

                    b.Property<string>("Role");

                    b.HasKey("Email");

                    b.ToTable("UserInfos");
                });

            modelBuilder.Entity("GLR_Backend_API_NET_CORE.Models.Course", b =>
                {
                    b.HasOne("GLR_Backend_API_NET_CORE.Models.Department")
                        .WithMany("Courses")
                        .HasForeignKey("DepartmentId");

                    b.HasOne("GLR_Backend_API_NET_CORE.Models.Student")
                        .WithMany("Courses")
                        .HasForeignKey("StudentId");

                    b.HasOne("GLR_Backend_API_NET_CORE.Models.Teacher")
                        .WithMany("Courses")
                        .HasForeignKey("TeacherId");
                });

            modelBuilder.Entity("GLR_Backend_API_NET_CORE.Models.Department", b =>
                {
                    b.HasOne("GLR_Backend_API_NET_CORE.Models.Organization")
                        .WithMany("Departments")
                        .HasForeignKey("OrganizationId");
                });

            modelBuilder.Entity("GLR_Backend_API_NET_CORE.Models.Leacture", b =>
                {
                    b.HasOne("GLR_Backend_API_NET_CORE.Models.Course")
                        .WithMany("Leactures")
                        .HasForeignKey("CourseId");
                });

            modelBuilder.Entity("GLR_Backend_API_NET_CORE.Models.Student", b =>
                {
                    b.HasOne("GLR_Backend_API_NET_CORE.Models.Department", "department")
                        .WithMany("Students")
                        .HasForeignKey("departmentId");
                });

            modelBuilder.Entity("GLR_Backend_API_NET_CORE.Models.Teacher", b =>
                {
                    b.HasOne("GLR_Backend_API_NET_CORE.Models.Department")
                        .WithMany("Teachers")
                        .HasForeignKey("DepartmentId");
                });
#pragma warning restore 612, 618
        }
    }
}
